#!/bin/sh
#PBS -N log_optimization
#PBS -M jpearkes@uvic.ca
#PBS -l walltime=1:00:00
#PBS -l mem=4gb
#PBS -l procs=1
#PBS -j oe
#PBS -r n

cd /home/jpearkes/HiggsChallenge/code
echo "Current working directory is `pwd`"
module load python 
echo "Starting run at: `date`"
python logistic_sgd.py $input1 $input2 $input3 $input4 $input5 $input6 $input7  
echo "Program logistic_sgd finished with exit code $? at: `date`"
