#!/bin/sh
#PBS -N mlp_optimization
#PBS -M jpearkes@uvic.ca
#PBS -l walltime=1:00:00
#PBS -l mem=4gb
#PBS -l procs=1
#PBS -j oe
#PBS -r n

cd /home/jpearkes/HiggsChallenge/code
echo "Current working directory is `pwd`"
module load python 
echo "Starting run at: `date`"
python mlp.py $input1 $input2 $input3 $input4 $input5 $input6 $input7 $input8 $input9 
echo "Program mlp finished with exit code $? at: `date`"